hungryhelpers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('findLocation/', include('findLocation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    #path('hungry_helpers_bootstrap/', include('hungry_helpers_bootstrap.urls')),
    #path('forms/', include('forms.urls')),
    path('notifs/', include('notifs.urls')),
    path('mealPlan/', include('mealPlan.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

mealPlan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
#from mealPlan.views import mealPlanView

urlpatterns = [
    #path('', mealPlanView.as_view(), name='index'),
    path('', views.meal_plan, name='meal_plan'),
    path('ticket_add/', views.ticket_add, name='ticket_add'),
    path('staffPage/', views.staffPage, name='staffPage'),
    path('send_confirm_notif/', views.sendConfirmNotif, name='send_confirm_notif'),
]

notifs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import notifications.urls
from django.conf.urls import url

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('message', views.message, name='message'),
    path('inbox/', views.inbox, name='inbox'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

findLocation/models.py
from django.db import models
from django.contrib.auth.models import User


class GoogleMapsResponse(models.Model):
    #id = models.CharField(max_length = 100, primary_key = True)
    location = models.TextField(default=0) # location textfield
    distance = models.FloatField(default=0)
    time = models.TextField(default=0)
    school = models.TextField(default=0)
    bus = models.TextField(default=0)
    timeframe = models.TextField(default=0) # distribution time for pickup
    address = models.TextField(default=0) # location address
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    class Meta:
        db_table = "findLocation_googlemapsresponse"

class Origin(models.Model):
    user = models.ForeignKey(User, null=True, related_name="originID", on_delete=models.CASCADE)
    #id = models.CharField(max_length=100, primary_key=True)
    origin = models.TextField(default=0)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    class Meta:
        db_table = "findLocation_origin"

mealPlan/models.py
from django.db import models
from django.contrib.auth.models import User
from findLocation.models import GoogleMapsResponse


# Create your models here.


# perspective of staff adding a new meal to the database
class Meal(models.Model):
    content = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now=True)

    celiac = models.BooleanField(default=False)
    shellfish = models.BooleanField(default=False)
    lactose = models.BooleanField(default=False)

    halal = models.BooleanField(default=False)
    kosher = models.BooleanField(default=False)
    vegetarian = models.BooleanField(default=False)

    #location = models.CharField(max_length=500, default="none")
    location = models.ForeignKey(GoogleMapsResponse, on_delete=models.CASCADE)

class notifMsg(models.Model):
    confirm = models.IntegerField(default=0)

mealPlan/forms.py
from django import forms
from mealPlan.models import Meal, notifMsg


class mealPlanForm(forms.ModelForm):
    content = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "New Meal Name"}))

    celiac = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    shellfish = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    lactose = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))

    halal = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    kosher = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    vegetarian = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))

    location = forms.CharField(widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Meal
        fields = ('content',)

class confirmPlan(forms.ModelForm):
    confirm = forms.IntegerField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}))

    class Meta:
        model = notifMsg
        fields = ('confirm',)

mealPlan/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.views.generic import DetailView, TemplateView
from mealPlan.forms import mealPlanForm, confirmPlan
from mealPlan.models import Meal
from accounts.models import Student, MealPlan
from findLocation.models import GoogleMapsResponse
from notifications.signals import notify


def meal_plan(request):
    form = mealPlanForm()
    # get all content from Meal objects
    meals = Meal.objects.all()

    googlemaps = GoogleMapsResponse.objects.all()

    args = {'form': form, 'meals': meals, 'googlemaps': googlemaps}

    return render(request, 'mealPlan/index.html', args)


def ticket_add(request):
    # create meal object using content from form and save
    meal_text = request.POST['content']

    restrictions = {'celiac': request.POST.get('Celiac', False), 'shellfish': request.POST.get('Shellfish', False),
                    'lactose': request.POST.get('Lactose', False), 'halal': request.POST.get('Halal', False),
                    'kosher': request.POST.get('Kosher', False), 'vegetarian': request.POST.get('Vegetarian', False)}

    for restriction in restrictions:
        if restrictions[restriction] == 'on':
            restrictions[restriction] = True

    location = int(request.POST.get("locations", "none"))
    location2 = GoogleMapsResponse.objects.get(id=location)

    new_meal = Meal(content=meal_text, celiac=restrictions['celiac'],
                    shellfish=restrictions['shellfish'], lactose=restrictions['lactose'],
                    halal=restrictions['halal'], kosher=restrictions['kosher'],
                    vegetarian=restrictions['vegetarian'], location=location2)

    new_meal.save()
    return HttpResponseRedirect(reverse('meal_plan'))

def sendConfirmNotif(request):
    mealPk = request.POST.get("mealPk", 0)
    print(mealPk)
    if mealPk != "none":
        sender = User.objects.get(username=request.user)
        mealObj = MealPlan.objects.get(id=mealPk)
        userPk = mealObj.student_profile.user_account.user.pk
        studObj = mealObj.student_profile
        receiver = User.objects.get(id=userPk)
        locationInfo = mealObj.pickup_location
        loc = locationInfo[:locationInfo.index(':')]
        #print(mealPk)
        notify.send(sender, recipient=receiver, verb=mealPk,
                    description=str(studObj.first_name) + " " + str(studObj.last_name) + "'s meal is ready for pick up at " + str(loc) + "!")
        return HttpResponseRedirect(reverse('staffPage'))

def staffPage(request):
    form = confirmPlan()
    mealplans = MealPlan.objects.all()
    #googlemaps = GoogleMapsResponse.objects.all()
    context={'mealplans': mealplans, 'form': form}
    return render(request, 'mealPlan/staffpage.html', context)

mealPlan/templates/mealPlan/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

{% if user.is_authenticated and perms.mealplan.add_meal%}

<div class="container-fluid">
<div class="card shadow mb-3">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">Create a New Meal</p>
    </div>
    <div class="card-body">
        <form action="{% url 'ticket_add' %}" method="post">
            {% csrf_token %}
            {{ form.content }}
            <br>

            <p class="text-primary m-0 font-weight-bold">Location</p>
            <div>
<!---
                <input type="hidden" id="location_key" name="location_key">
                {% for place in googlemaps %}
                <option>{{ place.pk }}</option>
                {% endfor %}
     --->
            <label for="locations">Choose a Location:</label>
                <br>
            <select name="locations" id="id_location" select>
                {% for place in googlemaps %}
                <option value= {{ place.pk }}>{{ place.location }}</option>
                {% endfor %}
            </select>

            </div>
            <br>

            <p class="text-primary m-0 font-weight-bold">Allergies</p>
            <div id="allergies">

                <input type="checkbox" name="Celiac" id="1" class='chk-btn'>
                <label for='1'>Celiac</label>

                <input type="checkbox" name="Shellfish" id="2" class='chk-btn'>
                <label for='2'>Shellfish</label>

                <input type="checkbox" name="Lactose" id="3" class='chk-btn'>
                <label for='3'>Lactose</label>

            </div>
            <br>
            <p class="text-primary m-0 font-weight-bold">Preferences</p>
            <div id="preferences">

                <input type="checkbox" name="Halal" id="4" class='chk-btn'>
                <label for='4'>Halal</label>

                <input type="checkbox" name="Kosher" id="5" class='chk-btn'>
                <label for='5'>Kosher</label>

                <input type="checkbox" name="Vegetarian" id="6" class='chk-btn'>
                <label for='6'>Vegetarian</label>

            </div>
            <br>
            <button type="submit" class="btn btn-primary btn-block text-white btn-user">Submit</button>
        </form>
    </div>
</div>

<div class="card shadow mb-3">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">All Meals</p>
    </div>
    <div class="card-body">
        <ol>
            {% for meal in meals %}
            <li> {{ meal.content }}</li>
            <p> Location: {{meal.location.location }}</p>
            <p> Celiac: {{ meal.celiac }}, Shellfish: {{ meal.shellfish }}, Lactose: {{ meal.lactose }} </p>
            <p> Halal: {{ meal.halal }}, Kosher {{ meal.kosher }}, Vegetarian: {{ meal.vegetarian }} </p>
            {% endfor %}
        </ol>
    </div>
</div>
</div>

{% else %}
    You must be an administrator or a staff user to access this page!
{% endif %}

{% endblock %}

mealPlan/templates/mealPlan/staffPage.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


{% if user.is_authenticated and perms.findLocation.add_googlemapsresponse %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <div class="container-fluid">
        <h3 class="text-dark mb-4">Student Meal Plans</h3>
        <div class="row">
            <div class="col">
                <div class="card shadow mb-3">
                    <div class="card-header py-3">
                        <p class="text-primary m-0 font-weight-bold">Meal Plan Tickets</p> </br>
                        <div class="col-xs-4">
                            <input class="form-control" id="myInput" type="text" placeholder="Search..">
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">First</th>
                                    <th scope="col">Last</th>
                                    <th scope="col">Pickup Location</th>
                                    <th scope="col">Confirmation Number</th>
                                    <th scope="col">Confirm</th>
                                </tr>
                                </thead>
                                <tbody id="myTable">
                                {% for mealplan in mealplans %}
                                    {% if mealplan.complete == "Yes" %}
                                        <tr>
                                            <td>{{ mealplan.student_profile.user_account.user.first_name }}</td>
                                            <td>{{ mealplan.student_profile.user_account.user.last_name }}</td>
                                            <td>{{ mealplan.pickup_location }}</td>
                                            <td>{{ mealplan.pk }}</td>
                                            {% csrf_token %}
                                            {{ form.content }}
                                            <form method="POST" action="{% url 'send_confirm_notif' %}">
                                                {% csrf_token %}
                                                <td><button type="submit" name="mealPk" class="btn btn-outline-success" value="{{ mealplan.pk }}">Confirm</button></td>
                                            </form>

                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% else %}
    You must be logged in or have access to use this page!
{% endif %}

{% endblock %}