hungryhelpers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('findLocation/', include('findLocation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    #path('hungry_helpers_bootstrap/', include('hungry_helpers_bootstrap.urls')),
    #path('forms/', include('forms.urls')),
    path('notifs/', include('notifs.urls')),
    path('mealPlan/', include('mealPlan.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

notifs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import notifications.urls
from django.conf.urls import url

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('message', views.message, name='message'),
    path('inbox/', views.inbox, name='inbox'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

accounts/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.urls import reverse
from localflavor.us.us_states import STATE_CHOICES
from .static_info import AGE_CHOICES, GRADE_CHOICES, DISTRICTS, SCHOOLS, PICKUP_CHOICES, TIMES, DAYS

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, null=True, blank=False)
    city = models.CharField(max_length=255, null=True, blank=False)
    state = models.CharField(max_length=2, choices=STATE_CHOICES, null=True, blank=False)
    zip = models.CharField(max_length=33, null=True, blank=False)
    district = models.CharField(max_length=255, choices=DISTRICTS, null=True, blank=False)
    school = models.CharField(max_length=255, null=True, choices=SCHOOLS, blank=False)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('home')

class Student(models.Model):
    user_account = models.ForeignKey(Profile, related_name="students", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, blank=False)
    last_name = models.CharField(max_length=255, blank=False)
    age = models.IntegerField(choices=AGE_CHOICES)

    school = models.CharField(max_length=255, choices=SCHOOLS, blank=False)
    grade = models.IntegerField(choices=GRADE_CHOICES)
    student_id = models.CharField(max_length=255, blank=False)
    #pickup_location = models.CharField(max_length=255, null=True, blank=False)

    allergic_celiac = models.CharField(max_length=255, null=True, default="No")
    allergic_shellfish = models.CharField(max_length=255, null=True, default="No")
    allergic_lactose = models.CharField(max_length=255, null=True, default="No")

    preference_halal = models.CharField(max_length=255, null=True, default="No")
    preference_kosher = models.CharField(max_length=255, null=True, default="No")
    preference_vegetarian = models.CharField(max_length=255, null=True, default="No")

    def __str__(self):
        return '%s' % (str(self.first_name) + " " + str(self.last_name))

class MealPlan(models.Model):
    student_profile = models.ForeignKey(Student, related_name="mealplan", on_delete=models.CASCADE)
    pickup_type = models.CharField(max_length=255, null=True, choices=PICKUP_CHOICES)
    day = models.CharField(max_length=255, null=True, choices=DAYS)
    time = models.CharField(max_length=255, null=True, choices=TIMES)
    meal_breakfast = models.CharField(max_length=255, null=True, default="No")
    meal_lunch = models.CharField(max_length=255, null=True, default="No")
    meal_dinner = models.CharField(max_length=255, null=True, default="No")

    pickup_location = models.CharField(max_length=255, null=True, blank=True)
    complete = models.CharField(max_length=255, null=True, default="No", blank=True)

    def __str__(self):
       return '%s' % (self.student_profile)

findLocation/models.py
from django.db import models
from django.contrib.auth.models import User


class GoogleMapsResponse(models.Model):
    #id = models.CharField(max_length = 100, primary_key = True)
    location = models.TextField(default=0) # location textfield
    distance = models.FloatField(default=0)
    time = models.TextField(default=0)
    school = models.TextField(default=0)
    bus = models.TextField(default=0)
    timeframe = models.TextField(default=0) # distribution time for pickup
    address = models.TextField(default=0) # location address
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    class Meta:
        db_table = "findLocation_googlemapsresponse"

class Origin(models.Model):
    user = models.ForeignKey(User, null=True, related_name="originID", on_delete=models.CASCADE)
    #id = models.CharField(max_length=100, primary_key=True)
    origin = models.TextField(default=0)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    class Meta:
        db_table = "findLocation_origin"

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load notifications_tags %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Hungry Helpers</title>
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/css/Contact-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/css/Contact-Form-v2-Modal--Full-with-Google-Map.css' %}">
    <link rel="stylesheet" href="{% static 'hungryhelpers/assets/css/Map-Clean.css' %}">
</head>

<body id="page-top">
    <div id="wrapper">
        <!-- Side bar content -->
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-laugh-wink"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>Hungry Helpers</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    {% if user.is_authenticated %}
                        {% if user.profile.id %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'home' %}"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'show_profile' %}"><i class="fas fa-user"></i><span>Profile</span></a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'meal_plans' %}"><i class="fas fa-utensils"></i><span>Meal Plans</span></a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'inbox' %}"><i class="fas fa-bell"></i><span>Notifications</span></a></li>
                            <!--<li class="nav-item"><a class="nav-link" href="{% url 'findlocation' %}"><i class="fa fa-map"></i><span>Map</span></a></li>-->
                            <li class="nav-item"><a class="nav-link" href="{% url 'edit_settings' %}"><i class="fas fa-cog"></i><span>Settings</span></a></li>
                            {% if perms.mealplan.add_mealplan%}
                            <!--<li class="nav-item"><a class="nav-link" href="{% url 'meal_plan' %}"><i class="fas fa-plus"></i><span>Add Meals</span></a></li>-->
                            {% endif %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-door-open"></i><span>Log Out</span></a></li>
                            {% if perms.findLocation.add_googlemapsresponse %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'administration' %}"><i class="fas fa-unlock"></i><span>Administration</span></a></li>
                            {% endif %}
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'create_profile' %}"><i class="fas fa-user"></i><span>Profile</span></a></li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item"><a class="nav-link active" href="{% url 'home' %}"><i class="fas fa-info-circle"></i><span>About Us</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}"><i class="far fa-user-circle"></i><span>Login</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}"><i class="fas fa-user-circle"></i><span>Register</span></a></li>
                    {% endif %}
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <!-- Header bar content -->
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <!-- (Search Bar)
                        <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <div class="input-group"><input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
                                <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                            </div>
                        </form>
                        -->
                        <ul class="navbar-nav flex-nowrap ml-auto">
                          <!-- (Search Bar)
                          <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto navbar-search w-100">
                                        <div class="input-group"><input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
                                            <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                                        </div>
                                    </form>
                                </div>
                            </li>-->
                            {% if user.is_authenticated %}

                                <div class="nav-item dropdown no-arrow mx-1">
                                    <a href="#" class="notification dropdown-toggle nav-link" aria-expanded="false" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true">
                                        <i class="fas fa-bell" style="font-size:24px"></i>
                                        <span class="badge">{% live_notify_badge %}</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                        <div class="dropdown-divider"></div>
                                        {% for notification in user.notifications.unread %}
                                            &nbsp;<a href="{% url 'inbox' %}"><span>New Message From Staff</span></a>
                                            <div class="dropdown-divider"></div>
                                        {% endfor %}
                                    </div>
                                </div>
                                {% live_notify_list list_class="dropdown-menu" %}

                                <!--<li class="nav-item dropdown no-arrow mx-1">
                                    <div class="nav-item dropdown no-arrow">
                                        <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="badge badge-danger badge-counter">0</span><i class="fas fa-bell fa-fw"></i></a>
                                        Add notification functionality
                                    </div>
                                </li>-->
                            {% endif %}
                            <!--<li class="nav-item dropdown no-arrow mx-1">
                                 (Mail icon)
                                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="badge badge-danger badge-counter">0</span><i class="fas fa-envelope fa-fw"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-list animated--grow-in">
                                        Add mail functionality
                                    </div>
                                </div>
                                <div class="shadow dropdown-list dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown"></div>
                            </li>-->
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                {% if user.is_authenticated  %}
                                    {% if user.profile.id %}
                                        <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">{{ user.username }}</span><img class="border rounded-circle img-profile" src="{% static 'hungryhelpers/assets/img/avatars/loggedin.jpg' %}"></a>
                                            <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                              <a class="dropdown-item" href="{% url 'show_profile' %}"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Profile</a>
                                              <a class="dropdown-item" href="{% url 'edit_settings' %}"><i class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Settings</a>
                                              <div class="dropdown-divider"></div>
                                              <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
                                            </div>
                                        </div>
                                    {% else %}
                                         <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">{{ user.username }}</span><img class="border rounded-circle img-profile" src="{% static 'hungryhelpers/assets/img/avatars/loggedin.jpg' %}"></a>
                                            <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                            <a class="dropdown-item" href="{% url 'create_profile' %}"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Profile</a>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% else %}
                                    <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">You are not logged in</span><img class="border rounded-circle img-profile" src="{% static 'hungryhelpers/assets/img/avatars/loggedout.jpg' %}"></a>
                                        <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                          <a class="dropdown-item" href="{% url 'login' %}"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Login</a>
                                          <div class="dropdown-divider"></div>
                                          <a class="dropdown-item" href="{% url 'signup' %}"><i class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Register</a>
                                        </div>
                                    </div>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </nav>
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
    <!--
    <footer class="bg-white sticky-footer">
        <div class="container my-auto">
            <div class="text-center my-auto copyright"><span>Copyright © Brand 2021</span></div>
        </div>
    </footer>

    <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    -->
    <script src="{% static 'hungryhelpers/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'hungryhelpers/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'hungryhelpers/assets/js/chart.min.js' %}"></script>
    <script src="{% static 'hungryhelpers/assets/js/bs-init.js' %}"></script>
    <script src="{% static 'hungryhelpers/assets/js/Contact-Form-v2-Modal--Full-with-Google-Map.js' %}"></script>
    <script src="{% static 'hungryhelpers/assets/js/theme.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
</body>
</html>

templates/base_notifs.html
{% load static %}
{% load notifications_tags %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
    Hungry Helpers
    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Hungry Helpers</a>
    <div class="dropdown">
      <a href="#" class="notification dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true">
        <i class="fa fa-bell" style="font-size:24px"></i>
        <span class="badge">{% live_notify_badge %}</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        {% for notification in  user.notifications.unread %}
        <div>
          Message from <b>{{ notification.actor }}</b>
          <button class="dropdown-item" type="button">{{ notification.description }}</button>
        </div>
        <div class="dropdown-divider"></div>
        {% endfor %}
      </div>
    </div>
    {% live_notify_list list_class="dropdown-menu" %}
    {% if user.is_authenticated %}
    <a class="nav-brand" href="#">{{ user.username }}</a>
    {% else %}
    <a class="nav-brand" href="#">Hello Guest user</a>
    {% endif %}
  </div>
</nav>

<body>

<div class="container">
  {% block content %}
  {% endblock %}
</div>
</body>

<style>
  .notification {
    color: white;
    text-decoration: none;
    padding: 15px 26px;
    position: relative;
    display: inline-block;
    border-radius: 2px;
  }

  .notification .badge {
    position: absolute;
    top: 2px;
    right: 30px;
    padding: 5px 10px;
    border-radius: 50%;
    background-color: red;
    color: white;
  }
</style>
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}

</html>

templates/base_prev.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}User Authentication{% endblock %}</title>
</head>
<body>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/dropdown.html
<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
    {% for notification in  user.notifications.unread %}
    <div>
        Message from <b>{{ notification.actor }}</b>
        <button class="dropdown-item" type="button">{{ notification.description }}</button>
    </div>
    <div class="dropdown-divider"></div>
    {% endfor %}
</div>

templates/home.html
{% extends 'base.html' %}
{% block title %}Create Profile{% endblock %}
{% block content %}

{% load static %}

{% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="d-sm-flex justify-content-between align-items-center mb-4">
            <h3 class="text-dark mb-0">Dashboard</h3>
        </div>
        <hr>
        <h2> Good evening, {{ user.first_name }}! </h2>
        <div class="row">
            <div class="col">
                {% if user.profile.address == '' %}
                    <div class="card shadow mb-3">
                        <div class="card-header ">
                            <p class="text-danger m-0 font-weight-bold h3" style="text-align:center">Complete Your Profile!</p>
                        </div>
                        <div class="card-body bg-warning">
                            <div class="row ">
                                <i class="fa fa-compass fa-5x fa-fw"></i>
                                <div class="col">
                                    <h4 style="color:grey;"> Be sure to update your profile with your address to locate pickup locations near you! <br></h4>
                                </div>
                            </div>
                            <div style="display: inline-block; margin-left: 42%;" >
                                <div class="row">
                                    <a href="{% url 'edit_profile' %}" class="btn btn-block btn-danger" style="text-align:center;">Update Your Location!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="card shadow mb-3">
                    <div class="card-header">
                        <p class="text-primary m-0 font-weight-bold h3" style="text-align:center">School Alert</p>
                    </div>
                    <div class="card-body">
                        <div class="row ">
                            <i class="fa fa-bullhorn fa-5x fa-fw"></i>
                            <div class="col">
                                <h4> BCPS summer school meals now scheduling available at no cost, to all children ages 2-18 curbsize pickup. <br>
                                <b> Monday + Wednesday </b> <br>
                                11:00 AM - 1:00PM</h4>
                            </div>
                        </div>
                        <div style="display: inline-block; margin-left: 35%;" >
                            <div class="row">
                                <a href="#"><button style="width:155px; text-align:center;" type="button" class="btn btn-primary btn-block">Create Meal Plan</button></a>
                                &emsp;
                                <a href="#"><button style="width:155px; text-align:center;" type="button" class="btn btn-secondary btn-block">Dismiss</button></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card shadow mb-3">
                    <div class="card-header">
                        <p class="text-primary m-0 font-weight-bold h3" style="text-align:center">Your Schedule</p>
                    </div>
                    <div class="card-body">
                        <div class="row ">
                            <i class="fa fa-calendar-plus fa-5x fa-fw"></i>
                            <div class="col">
                                <h4> Set up your pick up or delivery method for your meal plans </h4>
                            </div>
                        </div>
                        <div style="display: inline-block; margin-left: 44%;" >
                            <div class="row">
                                <a href="#"><button style="width:155px; text-align:center;" type="button" class="btn btn-primary btn-block">View</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>
{% else %}
    <div class="container-fluid">
        <div class="d-sm-flex justify-content-between align-items-center mb-4">
            <h3 class="text-dark mb-0">Hungry Helpers Initiative</h3>
        </div>
        <hr>
        <h5>
            Since the COVID-19 pandemic, the distribution of subsidized meals has become an increasing concern
            due to social distancing and remote learning. Students who are qualified to receive school lunches
            are unfortunately unable to retrieve them effectively. With some districts suffering from reductions
            in their meal-service budget, this issue is only worsening. The current lunch program systems are
            difficult to navigate through, with no simple and flexible process for parents to benefit from.
            <br><br>
            In an effort to address this concern, Hungry Helpers have designed a web application to provide an
            organized and efficient system to distribute school lunches to public school students during the
            pandemic. It will provide a convenient and intuitive way for parents to plan when and where to pick
            up food and will also help school staff have an efficient structure for food pickups.
            <br><br>
            Parents can create an account which will save all of their children’s necessary information
            including dietary restrictions, school district, and more. They will then be able to sign up for free
            or reduced price lunch and choose from available times and locations to pick up their food that is flexible
            to their needs. This information will then be stored in a way that will be accessible to school staff.
            Parents will also receive real-time notifications regarding their pickup and any changes that will occur.
            <br><br>
            The hope of Hungry Helpers is to help parents and schools take advantage of these lunch programs with ease!
        </h5>
        <hr>
        <form method="form" action="{% url 'login' %}">
            <button class="btn btn-primary btn-block btn-lg text-white btn-user" type="submit">Login Here!</button>
        </form>
        <br>
        <form method="form" action="{% url 'signup' %}">
            <button class="btn btn-primary btn-block btn-lg text-white btn-user" type="submit">Don't have an account? Sign up here!</button>
        </form>
    </div>
{% endif %}


{% endblock %}